sdkman/sdkman-db-migrations

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sdkman/sdkman-db-migrations/1)
> Fixing typos.

- src/main/scala/io/sdkman/changelogs/Migrations.scala
As discussed in [issue 629](https://github.com/sdkman/sdkman-cli/issues/629) i added the adoptopenjdk builds. But only the latest ones.
> Added openjdk build

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
- src/main/scala/io/sdkman/changelogs/Migrations.scala
Signed-off-by: Sven Marquardt <sven2q@hotmail.de>
geändert:       src/main/scala/io/sdkman/changelogs/Migrations.scala
> Add openjdk 9.0.4

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
This PR updates all Zulu JDKs to current versions.
> Update Zulu JDKs

- src/main/scala/io/sdkman/changelogs/BpipeMigrations.scala
This PR is to add Bpipe, a tool that I am the author of (see http://bpipe.org) to SDKMan.
Thanks!
> Add bpipe 0.9.9.5 to SDKMan

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
> Update default Java candidate to 8.0.181-zulu

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
As JDK 11 GA was released yesterday it is time to add it to sdkman.
> Add JDK11 GA version

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
> Add again GraalVM 1.0.0-RC7

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
Add Maven 3.6.0 and set it as the new default version
> Add Maven 3.6.0

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
GraalVM 1.0.0-RC9 released - https://github.com/oracle/graal/releases
> Add GraalVM 1.0.0-rc9 support

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
- src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
I also disabled the Java 11 ea migrations that are not working anymore because the URLs give 404
> add Spark 2.1.3

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes: https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc10
> Add GraalVM 1.0.0-RC10

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
> Deletes offending migrations that break tests

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/change-log.html#changes-2019-01-25b
> Update Amazon Corretto JDK 8u202

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes: https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc12
> Add GraalVM 1.0.0-RC12

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
This PR updates ZuluFX JDKs to current versions.
> Update ZuluFX JDKs

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
* https://aws.amazon.com/corretto/
* https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-corretto-11-is-now-in-preview/
> Add Amazon Corretto OpenJDK 11.0.2.9.1 (Preview)

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes: https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc13
> Add GraalVM 1.0.0-RC13

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes - https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc14
> added GraalVM 1.0.0-RC14 CE

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes - https://github.com/oracle/graal/tree/vm-1.0.0-rc15
> Add GraalVM 1.0.0-RC15 CE

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
We would like to add our OpenJDK distros to sdkman.
> Add BellSoft Liberica JDKs.

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
> Maven 3.6.1

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
```
Zulu 11.0.2  -> 11.0.3
Zulu 12.0.0  -> 12.0.1
SAP  11.0.2  -> 11.0.3
SAP  12.0.1
SAP  13.ea.16
```
> Java April Update Zulu/SAP

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes: https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc16
> Add GraalVM 1.0.0-RC16 CE

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes: https://www.graalvm.org/docs/release-notes/#1902
GitHub release information: https://github.com/oracle/graal/releases/tag/vm-19.0.2
> Add GraalVM CE 19.0.2

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Release notes: https://www.graalvm.org/docs/release-notes/#1910
GitHub release information: https://github.com/oracle/graal/releases/tag/vm-19.1.0
> Add GraalVM CE 19.1.0

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
7.0.232-zulu
8.0.222-zulu
11.0.4-zulu
12.0.2-zulu
> Add Java Zulu JDK July 2019 release

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
https://github.com/oracle/graal/releases/tag/vm-19.1.1
> Add GraalVM CE 19.1.1

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
> Add SapMachine July 2019 releases

- src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
> Add Scala 2.12.9

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
> * Added maven 3.6.2

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Hello, added BellSoft Liberica JDK 13.0.0.
Thanks
> Add Liberica JDK 13

- src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
Add Spark 2.4.4 to sdkman and make it default spark version
> PR to add Spark 2.4.4

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
https://www.graalvm.org/docs/release-notes/19_2/#1921
> Add Graal 19.2.1 and remove 19.2.0 & 19.2.0.1

- src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
Delete unavailable "OpenJDK 14 EA"
> Fix the migrate error

- src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
> Added AdoptOpenJDK 11.0.6

- src/main/scala/io/sdkman/changelogs/KarafMigrations.scala
Apache Karaf is a polymorphic application runtime (https://karaf.apache.org/) and is used in a similar area as the already existing "container frameworks" springboot, micronaut etc.
> Add karaf to be installable via sdkman.

- src/main/scala/io/sdkman/changelogs/ConcurnasMigrations.scala
Add Concurnas candidate migration script
> Add Concurnas to SDKMAN!

- src/main/scala/io/sdkman/changelogs/VisualVmMigrations.scala
Add a new migration with the last version of visualvm, 2.0.
> Update visualvm version to 2.0

- src/main/scala/io/sdkman/changelogs/DottyMigrations.scala
> fix(dotty): remove missing dotty 0.21.0 release

- src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
Signed-off-by: Kenji Saito <ken-yo@mbr.nifty.com>
> Liberica 2020-04-14 update

- src/main/scala/io/sdkman/changelogs/java/AzulZuluMigrations.scala
7.0.262-zulu
13.0.3-zulu
14.0.1-zulu
> Zulu 2020-04-14 update

- src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
> Add Scala 2.13.2

- src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
- src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
- src/main/scala/io/sdkman/changelogs/VisualVmMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/GraalVmMigrations.scala
Adds the latest stable release of Apache Spark (2.4.5)
> Add Apache Spark 2.4.5

- src/main/scala/io/sdkman/changelogs/DoctoolchainMigrations.scala
So, let's see if I understood everything the right way.
Here is my PR which adds docToolchain as one of the candidates and also adds the first version 1.2.0
`./gradlew clean run` runs with `BUILD SUCCESSFUL`:
```
[main] INFO com.github.mongobee.Mongobee - Mongobee is releasing process lock.
[main] INFO com.github.mongobee.Mongobee - Mongobee has finished his job.
BUILD SUCCESSFUL in 7m 39s
5 actionable tasks: 5 executed
```
> added docToolchain

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- Add OpenJDK 15ea29
- Add OpenJDK 16ea3
> openjdk 15 and 16

- src/main/scala/io/sdkman/changelogs/DottyMigrations.scala
Fixes #277 
There wasn't a typical artifact for 0.23.0 so I skipped it.
> Add Dotty 0.24.0

- src/main/scala/io/sdkman/changelogs/Http4kMigrations.scala
As per the instructions kindly provided, we're starting to add a CLI to http4k to generate pre-canned projects from modules (and a few other handy tools).
> Add http4k candidate (no version yet)

- src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
Hi @marc0der ,
I've addressed some of your comments from #288:
- implemented your suggestion from #284 
- got rid of merge
Can we do a housekeeping job a bit later? 
Should we move all necessary Liberica stuff from JavaMigrations to BellSoftLibericaMigrations?
> Liberica 8u262, 11.0.8, 14.0.2

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- Add OpenJDK 15ea32
- Add OpenJDK 16ea6
> openjdk 15ea32 and 16ea6

- src/main/scala/io/sdkman/changelogs/GradleProfilerMigrations.scala
This PR adds a new candidate for [Gradle profiler](https://github.com/gradle/gradle-profiler).
> Add Gradle profiler 0.12.0

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- Add OpenJDK 15ea33
- Add OpenJDK 16ea7
> Add OpenJDK 15ea33 and 16ea7

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- Add OpenJDK 15ea34
- Add OpenJDK 16ea8
> Add OpenJDK 15ea34 and 16ea8

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- Add OpenJDK 15ea35
- Add OpenJDK 16ea9
> Add OpenJDK 15ea35 and 16ea9

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- Fix binaries for OpenJDK 15ea35
- Fix format
> Fix OpenJDK 15ea35

- src/main/scala/io/sdkman/changelogs/java/AzulZuluFxMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/AzulZuluMigrations.scala
- Zulu 8u265(https://github.com/sdkman/sdkman-db-migrations/pull/309/commits/8660fa0b7496f67c8d24baca743213f9a9da3721)
- Zulu FX 8u265(https://github.com/sdkman/sdkman-db-migrations/pull/309/commits/4d88e1a69d16a0cf7290502090ea6f3fe8f604e4)
- Zulu FX 8u262(https://github.com/sdkman/sdkman-db-migrations/pull/309/commits/d814d6d99900c8c385f26b71eeced0058519110a)
> Added Zulu 8u265 and ZuluFX 8u265

- src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
Adds LTS versions of Liberica for Linux ARM64 (AArch64)
> Adds Linux ARM64 librca versions 8,11,11fx,14,14fx

- src/main/scala/io/sdkman/changelogs/MavenDaemon.scala
> Add mvnd candidate

- src/main/scala/io/sdkman/changelogs/java/MandrelMigrations.scala
- src/main/scala/io/sdkman/changelogs/package.scala
The only binary version on github for now
> Add Mandrel to JDK family

- src/main/scala/io/sdkman/changelogs/VisualVmMigrations.scala
> Add VisualVM 2.0.4

- src/main/scala/io/sdkman/changelogs/DottyMigrations.scala
> Add Dotty migration to 0.27.0-RC1

- src/main/scala/io/sdkman/changelogs/BallerinaMigrations.scala
> Ballerina candidate added

- src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
> Fixed a mistake in the Liberica FX ID format.

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
see https://docs.gradle.org/nightly/userguide/toolchains.html#sec:auto_detection
> Add OpenJDK 16ea6 Loom Early Access

- src/main/scala/io/sdkman/changelogs/java/AzulZuluFxMigrations.scala
> Remove broken ZuluFX version 13.0.4, add ZuluFX version 13.0.4 and 14.0.2

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
Migration to openjdk_java_16-ea-19
Closes gh-330
> Openjdk_java_16-ea-19 migration

- .github/auto_assign.yml
- .github/workflows/action.yml
Add a basic workflow that:
* adds reviewers
* assigns the author
> Add initial github worflow.

- .sdkmanrc
> Add .sdkmanrc

- .github/workflows/run.yml
This github action will:
* checkout the code
* start mongo 3.2
* ./gradlew run
> Run local migration for every PR.

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
> Add OpenJDK 16ea20

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
closes #332
hopefully this is correct. I was not 100% sure.
> Add OpenJDK 16ea21

- src/main/scala/io/sdkman/changelogs/java/AzulZuluMigrations.scala
* Add zulu8.50.0.21-ca-jdk8.0.272
* Add zulu11.43.21-ca-jdk11.0.9
* Add zulu13.35.17-ca-jdk13.0.5
* Add zulu15.28.13-ca-jdk15.0.1
* Add zulu7.42.0.13-ca-jdk7.0.282
> Add Zulu 7.0.282/8.0272/11.0.9/13.0.5/15.0.1

- src/main/scala/io/sdkman/changelogs/java/AlibabaDragonwellMigrations.scala
- src/main/scala/io/sdkman/changelogs/package.scala
> Add Dragonwell JDK 8 & 11

- src/main/scala/io/sdkman/changelogs/java/AzulZuluFxMigrations.scala
Added the Zulu FX.
- Zulu FX 8.50.0.21 (8.0.272)
- Zulu FX 15.28.13 (15.0.1)
- Zulu FX 13.35.17 (13.0.5)
- Zulu FX 11.43.21 (11.0.9)
> Added the ZuluFX 8u272/15.0.1/13.0.5/11.0.9

- src/main/scala/io/sdkman/changelogs/IndexMigrations.scala
> Add compound index for `versions` collection

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
> Add OpenJDK 16 EA 22

- src/main/scala/io/sdkman/changelogs/java/SapMachineMigrations.scala
> Update the SapMachine 11.0.9 to 11.0.9.1

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
> Add OpenJDK 16ea28

- src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/AzulZuluFxMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/AzulZuluMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/GraalVmMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- src/main/scala/io/sdkman/changelogs/package.scala
Set visible false to some java candidates.
> Add hideVersion

- src/main/scala/io/sdkman/changelogs/package.scala
See sdkman/sdkman-candidates#22
> Add Eclipse Temurin vendor

- src/main/scala/io/sdkman/changelogs/java/GraalVmMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
- Hide 15.0.1-open
- Hide 20.3.0.r8-grl and 20.3.0.r11-grl
> hide java1501 graalvm2030

- src/main/scala/io/sdkman/changelogs/java/AmazonCorrettoMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/SapMachineMigrations.scala
- Hide 8.0.275-amzn and 11.0.9-amzn
- Hide 8.0.275, 11.0.9, 15.0.1 for librca
> hide amz librca

- src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/AmazonCorrettoMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/AzulZuluFxMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/AzulZuluMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
Hide old versions and no lts versions for the different vendors. Just keep last no lts version 15.
> Hide java versions

- src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
Depends on https://github.com/sdkman/sdkman-db-migrations/pull/467
> Hide old EA OpenJDK versions

- src/main/scala/io/sdkman/changelogs/java/MandrelMigrations.scala
Removes obsolete 20.1.0.3 and 20.2.0.0.
Replaces 20.3.1.2 and 21.0.0.0 with respins (same code but with different versioning scheme) due to https://github.com/graalvm/mandrel/issues/218
> Mandrel: Remove old versions and replace 21.0 and 20.3 with respins

- src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
> Fix adoptopenjdk 8.0.272 - second round

- src/main/scala/io/sdkman/changelogs/JdkMissionControlMigrations.scala
- src/main/scala/io/sdkman/changelogs/package.scala
* Add JMC candidate
* Add the Oracle Vendor for official JMC
* Clean up boilerplate code
> Add JMC candidate.

- src/main/scala/io/sdkman/changelogs/AntMigration.scala
> Add Ant 1.10.10

- src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
> Add Scala 3.0.0

- src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
> Add Scala 2.13.6

- src/main/scala/io/sdkman/changelogs/HadoopMigrations.scala
> feat(Hadoop) - Adding Apache Hadoop changelog

- src/main/scala/io/sdkman/changelogs/ConnorMigration.scala
> Add Connor candidate

- src/main/scala/io/sdkman/changelogs/ConnorMigration.scala
Just a small change to the name and description to be in line with the GitHub repo's description.
> Update connor candidate name and description

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
Hi,
Simple PR in order to add Maven 3.8.2.
> Add Maven 3.8.2

- src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
> Add Scala 3.0.1

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
https://twitter.com/ASFMavenProject/status/1444951811601932290?s=20
> Add Maven 3.8.3

- src/main/scala/io/sdkman/changelogs/PierrotMigrations.scala
This PR adds a candidate and the latest version of Pierrot CLI to SDKMAN.
> Pierrot candidate and initial version

- src/main/scala/io/sdkman/changelogs/KcctlMigrations.scala
Hi, this adds a migration for kcctl.
> Adding kcctl candidate

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
- src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
I update tomcat versions to the latest. Also, I set the default to 10.0.14.
> Update Tomcat versions to the latest #560

- src/main/scala/io/sdkman/changelogs/JMeterMigration.scala
Update with new JMeter versions and set the default to the latest version
> updating new jmeter versions and setting new default

- src/main/scala/io/sdkman/changelogs/KobwebMigrations.scala
... with initial steps to create a new candidate following steps
at https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process
> Introduce Migration for Kobweb

- src/main/scala/io/sdkman/changelogs/Neo4jMigrationsMigrations.scala
Hey there.
I would like to request an onboarding for a CLI called Neo4j-Migrations: A database refactoring tool for Neo4j, the graph database with the same name.
> Introduce migration for Neo4j-Migrations.

- src/main/scala/io/sdkman/changelogs/MyBatisMigrations.scala
Updating latest mybatis version 3.3.11 and setting it as the default
> updating latest mybatis version 3.3.11

- src/main/scala/io/sdkman/changelogs/ToolkitMigrations.scala
**Toolkit** is a client command line tool that supports multiple IoT protocols. for example, MQTT and COAP protocols,
Provide a user optimized client tool for IoT developers and learners
> add iot protocol client cli candidate named toolkit 

- src/main/scala/io/sdkman/changelogs/SkeletalMigrations.scala
Skeletal is an updated fork of the previously available Lazybones application.
> Add candidate for Skeletal

- src/main/scala/io/sdkman/changelogs/KtxMigrations.scala
Add https://github.com/mpetuska/ktx as sdkman candidate
> Add ktx candidate

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
This is my first contribution to this project and I used https://github.com/sdkman/sdkman-db-migrations/pull/621  as a template
Please let me know if I need to do anything else
> Add Maven 3.9.0

- src/main/scala/io/sdkman/changelogs/HelidonMigrations.scala
> Helidon migration

- src/main/scala/io/sdkman/changelogs/FlinkMigrations.scala
- src/main/scala/io/sdkman/changelogs/HadoopMigrations.scala
- src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
Hi SDKMAN team, thank you so much for providing this practical and useful tool.
I'd like to add the latest versions of Hadoop, Spark and Flink, so I'm submitting this PR.
I wrote this referring to past PRs and ensured that `./gradlew clean run` was successful, but let me know if there's something wrong because it's my first PR for SDKMAN.
> Add Hadoop 3.3.5, Spark 3.3.2 and Flink 1.17.0

- src/main/scala/io/sdkman/changelogs/DetektMigrations.scala
See https://github.com/detekt/detekt/issues/6086
> Adds Detekt as a new candidate

- src/main/scala/io/sdkman/changelogs/GcnMigrations.scala
- src/main/scala/io/sdkman/changelogs/package.scala
Graal Cloud Native GCN is an open source project (https://github.com/oracle/gcn) for cloud-native microservices.
First version we are submitting as PR, we will follow the vendor API process for future releases.
> GCN candidate

- src/main/scala/io/sdkman/changelogs/JExtractMigrations.scala
> chore: Add jextract candidate

- src/main/scala/io/sdkman/changelogs/DetektMigrations.scala
Adds detekt `1.23.0` and `1.23.1`.
> chore: Add detekt releases

- src/main/scala/io/sdkman/changelogs/JikkouMigrations.scala
The `jikkou` tool provides an efficient and easy way to manage, automate, and provision resource configurations for Kafka, Schema Registry, etc. SDKMAN! would simplify its installation.
> feat: add candidate jikkou

- .github/workflows/migrate.yml
- .github/workflows/pr.yml
- src/main/scala/io/sdkman/changelogs/JikkouMigrations.scala
> chore: Replace scalafmt with checkScalafmt

- src/main/scala/io/sdkman/changelogs/GraceMigrations.scala
Grace is a forked of Grails 5.1.x, started development in early 2022. An open-source and powerful One Person web application Framework to help developers quickly build Spring Boot applications written in the Groovy programing language. 
https://github.com/graceframework/grace-framework
Please review and merge, thank you.
> Add Grace candidate

- src/main/scala/io/sdkman/changelogs/AntMigration.scala
> chore: Add Ant 1.10.14

- src/main/scala/io/sdkman/changelogs/VisualVmMigrations.scala
- Add VisualVM 2.1.10.
- Fixes #708 .
> Add VisualVM 2.1.10

- src/main/scala/io/sdkman/changelogs/JettyMigrations.scala
Signed-off-by: Olivier Lamy <olamy@apache.org>
> Upgrade to Jetty 10.0.24, 11.0.24 and 12.0.14

- src/main/scala/io/sdkman/changelogs/HadoopMigrations.scala
Now the installation default to 3.4.1
> Updated Hadoop version to 3.4.1

- src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
Upgraded Spark version up untill 4.0.0-preview2
> Spark upgrade version 4.0.0 preview2

- src/main/scala/io/sdkman/changelogs/HscMigrations.scala
I would like to add [HTML Sanity Check (HSC)](https://hsc.aim42.org) to SDKman.
> Add HTML Sanity Check (HSC)

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
> Add Maven 4.0.0-rc-3

- src/main/scala/io/sdkman/changelogs/JMeterMigration.scala
Added last 3 versions of JMeter:
- 5.6.1
- 5.6.2
- 5.6.3
> Add new minor versions 5.6.x for JMeter

- src/main/scala/io/sdkman/changelogs/MavenMigration.scala
Also, because of #730, switch back to the repo.maven.apache.org URL
> Add Maven 4.0.0-rc4

- src/main/scala/io/sdkman/changelogs/VisualVmMigrations.scala
Updates VisualVM 2.2.
It is written similar to previous bump in https://github.com/sdkman/sdkman-db-migrations/pull/709
> Add VisualVM 2.2
