sdkman/sdkman-db-migrations

src/main/scala/io/sdkman/changelogs/GraalVMMigrations.scala
I've added the GraalVM CE migrations to make GraalVM available on the sdkman. I don't know how to test sdkman agains the local mongo, but the migrations against it run okay.
Currently, there binaries for GraalVM CE are only for Linux.
=> Add GraalVM migrations

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
The broken links that caused a partial revert of #14 have been fixed so this PR brings back those migrations. It also uses new validation mechanism that was introduced in #16.
This PR adds migrations with following links:
https://cdn.azul.com/zulu/bin/zulu6.20.0.1-jdk6.0.107-linux_x64.tar.gz
https://cdn.azul.com/zulu/bin/zulu6.20.0.1-jdk6.0.107-win_x64.zip
https://cdn.azul.com/zulu/bin/zulu7.23.0.1-jdk7.0.181-linux_x64.tar.gz
https://cdn.azul.com/zulu/bin/zulu7.23.0.1-jdk7.0.181-win_x64.zip
https://cdn.azul.com/zulu/bin/zulu7.23.0.1-jdk7.0.181-macosx_x64.tar.gz
https://cdn.azul.com/zulu/bin/zulu9.0.7.1-jdk9.0.7-linux_x64.tar.gz
https://cdn.azul.com/zulu/bin/zulu9.0.7.1-jdk9.0.7-win_x64.zip
https://cdn.azul.com/zulu/bin/zulu9.0.7.1-jdk9.0.7-macosx_x64.tar.gz
=> Update Zulu JDKs

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
This pull requests upgrades GraalVM to latest 1.0.0-RC4 version released 2 days ago (https://medium.com/graalvm/graalvm-1-0-rc4-release-notes-ba52bec3b4d7)
=> Adds graalvm 1.0.0-rc4

src/main/scala/io/sdkman/changelogs/CubaCliMigrations.scala
I've added the CUBA CLI migrations to make `cuba-cli` util available on the sdkman. For now, we distribute ZIP archive for Linux / Windows / Mac OS and its is platform specific archive.
=> Add CUBA CLI migrations

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
With this commit the EA candidates for Java 11 and 12 are added. 
Java 11 both has an Oracle and OpenJDK version, the Java 12 version
only has an OpenJDK version. 
The versioning is like *11.ea25-openjdk* as using *11.ea+25-openjdk* would 
result in a version longer then 15 characters. When the EA candidates can
be removed we can revert back to *11.0.0-openjdk* again.
=> Add Java 11 and 12 EA candidates

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Upgrade both Java 11 & 12 to the latest
EA releases of 23-8-2018.
=> Upgrade Java 11 & 12 EA Editions

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
This pull request adds GraalVM 1.0.0-RC7 (https://github.com/oracle/graal/releases)
=> Add GraalVM 1.0.0-rc7 support

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Now that Amazon Corretto provides archives for installation lets add them to sdkman. 
I choose `amzn` as the suffix not sure if we should choose something else?
See: https://github.com/corretto/corretto-8/issues/11
=> Add Amazon Corretto 8.0.192 (preview2)

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
This PR picks up the discussion in #49 and uses the naming schema suggested by @munukutla in his last comment: https://github.com/sdkman/sdkman-db-migrations/pull/49/files#r237146134
The OpenJ9 project itself links to the AdoptOpenJDK website for binary downloads, so using the suffix "-openj9" to identify AdoptOpenJDK OpenJDK builds with OpenJ9 should be fine.
Refs sdkman/sdkman-db-migrations#49
Refs eclipse/openj9#1924
=> Add OpenJDK 8u202 and 11.0.2 with OpenJ9 0.12.0

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Adding SapMachine 11.0.2 (LTS) release for Linux, Windows and MacOS. 
Question: SapMachine does also support Linux on PowerPC (Little and Big Endian), could this be of interest, too? Is sdkman supported on PowerPC? If so, I can add a few lines...
Also, is the suffix "sapmachine" fine or would you like to have something shorter? 
Thanks for your help and supporting SapMachine in sdkman!
=> Add SapMachine 11.0.2 for Linux, Windows and MacOS.

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
=> Update BellSoft Liberica JDKs, 12.0.1, 11.0.3 and 8u212.

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Added new entries for AdoptOpenJDK 12.0.1 for OpenJ9 and HotSpot variants.
Note, there is not Windows release for version 12.0.1 of the HotSpot variant, that I can see.
=> Add AdoptOpenJDK for 12.0.1 OpenJ9 and HotSpot

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Adding AdoptOpenJDK version 12.0.1 HotSpot for Windows again.
=> Adding AdoptOpenJDK 12.0.1 HotSpot for Windows

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
This PR add Graal 19.0.0 and removes old RC14. We'll keep RC15 and 16 for a while because the new one introduced some breaking changes.
=> Add Graal 19.0.0 and remove Graal RC14

src/main/scala/io/sdkman/changelogs/CubaCliMigrations.scala
Hi!
I'm from CUBA Platform Team.
We are migrating cuba-cli releases from Bintray to KeyCDN.
Links were in this format:
`https://cuba-platform.bintray.com/tools/cuba-cli/<VERSION>/cuba-cli-<VERSION>-linux.zip`
`https://cuba-platform.bintray.com/tools/cuba-cli/<VERSION>/cuba-cli-<VERSION>-macos.zip`
Now we have moved binaries to CDN and links look like:
`https://cdn.cuba-platform.com/cuba-cli/<VERSION>/cuba-cli-<VERSION>-linux.zip`
`https://cdn.cuba-platform.com/cuba-cli/<VERSION>/cuba-cli-<VERSION>-macos.zip`
=> Change CUBA CLI download URLs

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
As discussed on Slack, remove old Java `19.0.0-grl` superseded by `19.0.2-grl`.
=> Remove old Java 19.0.0-grl

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Hello,
Added new versions of Liberica JDK - 8u222, 11.0.4 and 12.0.2.
Thanks
=> Update BellSoft Liberica JDKs, 12.0.2, 11.0.4 and 8u222.

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Minor versions are rare in a JDK but Graal has them and there are breaking changes in 19.1. This restores the latest 19.0 release.
=> Restore GraalVM 19.0.2

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
SDKMAN currently offers `11.0.3.hs-adpt` as default Java candidate:
```bash
$ sdk ug
Upgrade:
java (7.0.232-zulu, 12.0.1.j9-adpt, 13.ea.30-open, 11.0.4.j9-adpt, 11.0.4.hs-adpt, 19.1.1-grl, 6.0.119-zulu, 14.ea.6-open, 8.0.222.hs-adpt, 8.0.222.j9-adpt, 12.0.1.hs-adpt < 11.0.3.hs-adpt)
Upgrade candidate(s) and set latest version(s) as default? (Y/n):
```
This PR updates default Java candidate to `11.0.4.hs-adpt`.
=> Update default Java candidate to 11.0.4.hs-adpt

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
This PR updates AdoptOpenJDK candidates:
- updates `12.0` to current versions
- adds `13.0`
=> Update AdoptOpenJDK candidates

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
**Note:** Unfortunately, AdoptOpenJDK doesn't build upstream binaries for macOS
=> Update AdoptOpenJDK 8 & 11, add upstream OpenJDK 8 & 11 (Linux & Windows)

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
New Liberica JDK builds - 8u232, 11.0.5 and 13.0.1.
Cleaned up old releases.
Thanks.
=> Added Liberica JDK 8u232, 11.0.5 and 13.0.1

src/main/scala/io/sdkman/changelogs/JavaMigrations.scala
Hotspot and J9 builds of AdoptOpenJDK 8.0.232, 11.05, 13.01
Also cleaned up superceded AdoptOpenJDK sdk defs that were removed, but left in code, by previous revisions.
=> AdoptOpenJDK 8.0.232, 11.05, 13.01

src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
There is no JDK13 in java.net repository now.
Due to the lack of `insert`, 13.0.2-open didn't be inserted.
https://github.com/sdkman/sdkman-db-migrations/blob/master/src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala#L523
Should I remove the ineffectual code in `018-add_openjdk_java_13.0.2`?
https://github.com/sdkman/sdkman-db-migrations/blob/master/src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala#L525-L547
=> Retry adding 13.0.2-open

src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
Current Java default candidate is outdated:
```
$ sdk ug
Upgrade:
java (11.0.7.j9-adpt, 8.0.252.hs-adpt, 14.0.1.hs-adpt, 14.0.1.j9-adpt, 8.0.252.j9-adpt, 11.0.7.hs-adpt < 11.0.6.hs-adpt)
Upgrade candidate(s) and set latest version(s) as default? (Y/n): 
```
=> Set 11.0.7.hs-adpt as default Java candidate

src/main/scala/io/sdkman/changelogs/java/SapMachineMigrations.scala
The download URL for '11.0.7-sapmchn' for macOS was from JRE.
Delete it and add the URL of the JDK.
=> Fix the SapMachine JDK for macOS download URL was wrong

src/main/scala/io/sdkman/changelogs/AntMigration.scala
I have no idea how this is going to look like with the existing versions of ant in the database, though. They're not in this repository. I'm mimicking what was doen with Maven here (which also has versions that are not here in the migrations)
=> Add recent Apache Ant versions

src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
OpenJDK 14.0.2's build number has changed from 11 to 12.
The download URL has also been changed.
To change to the new download URL, remove the original changeset and add a new URL changeset.
=> Readd the OpenJDK 14.0.2

src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
Hey @eddumelendez, found that I made a typo in #319 for the non FX versions. This results in alignment issues in the UI/CLI:
This PR removes the typos and replaces them with the right version ids.
=> Correction of linux arm64 version labels of 11, 14

.gitignore, README.md, build.gradle
I had to do the following changes to make development with vscode on Linux ARM64 possible on this repo:
- Updated Scale to version 2.12.12 (min supported Scala version in metals)
- Updated README to use docker container `mongo:4.0` (as this version and up have ARM64 support)
- Git ignore `.vscode` dir
Contributing this back, so that the next person doesn't have to 😉
=> Dev support for vscode on Linux ARM64

src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
This PR adds OpenJDK early access version 18 (https://download.java.net/java/early_access/jdk16/18/GPL/{binary_file})
=> Add OpenJDK 16ea18 (#329)

build.gradle
Runs `checkScalafmt` instead of `scalafmt` as dependent task on `compileScala`.
=> Fail build if code incorrectly formated.

.github/workflows/action.yml
Currently, when a PR is submitted by contributor from their own
fork, action is not running properly. In order to allow that
the action must use event `pull_request_target`.
=> Update event type to pull_request_target for action.xml

src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
Added the ChangeSet 33 to 36.
- AdoptOpenJDK 11.0.9 hotspot
- AdoptOpenJDK 11.0.9 openj9
- AdoptOpenJDK 15.0.1 hotspot
- AdoptOpenJDK 15.0.1 openj9.
ChangeSet 31 and 32 are will use by 8u272 hs/j9 in https://github.com/sdkman/sdkman-db-migrations/pull/385
=> Added the AdoptOpenJDK 11.0.9/15.0.1 hs/j9

src/main/scala/io/sdkman/changelogs/java/BellSoftLibericaMigrations.scala
Replace the Liberica JDK 11 and Liberica JDK 11 with FX.
- 11.0.9+11 to 11.0.9+12
=> Update Bellsoft Liberica JDK version to 11.0.9+12 (include FX)

src/main/scala/io/sdkman/changelogs/java/SapMachineMigrations.scala
It doesn't seem to exist for MacOS yet, so it's only for Linux and Windows.
- 11.0.9
- 15.0.1
=> Update the SapMachine 11.0.9/15.0.1 without MacOS

src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
* There is a fix on a license file for OpenJ9
* Shenandoah GC support in hotspot/jdk11 on Windows, Linux/x64 and Linux/aarch64
=> Update AdoptOpenJDK 11

src/main/scala/io/sdkman/changelogs/java/TravaOpenJdkMigrations.scala, src/main/scala/io/sdkman/changelogs/package.scala
TravaOpenJDK (https://github.com/TravaOpenJDK/trava-jdk-11-dcevm) builds AdoptOpenJDK with DCEVM enabled. DCEVM provides better hot swapping capabilities to Java HotSpot JVM (e.g. add/remove methods, redefine signatures... without full rebuild). It can be used in conjunction with HotSwapAgent to better integrate with various application frameworks (Spring, Hibernate...).
Looking at https://github.com/sdkman/sdkman-db-migrations/pull/413, I figured https://github.com/sdkman/sdkman-candidates/pull/19 will be needed as well.
=> Add TravaOpenJdk

src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
This commit introduced a scala3 aka dotty with version 3.0.0-M1.
=> Added Scala migration to 3.0.0-M1

src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
At present, this happens when using `upgrade` command with all the latest AdoptOpenJDK releases installed:
```
$ sdk ug
Upgrade:
java (21.0.0.r11-grl, 8.0.282.hs-adpt, 15.0.2.hs-adpt, 11.0.10.hs-adpt < 11.0.9.hs-adpt)
Upgrade candidate(s) and set latest version(s) as default? (Y/n):
```
This PR sets `11.0.10.hs-adpt` as the default Java candidate.
=> Update default Java candidate

src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala
PRs #466 and #463 are failing because link to OpenJDK Panama doesn't exist anymore
=> Remove 16.ea.3.pma-open migration

src/main/scala/io/sdkman/changelogs/java/AdoptOpenJdkMigrations.scala
Except for the Linux 64 Arm platform, all other platforms point to the 8.0.275 release.
This PR fixes the broken URLs.
=> Fix urls for AdoptOpenJDK 8.0.272

src/main/scala/io/sdkman/changelogs/ScalaMigrations.scala
Pull Request opened for issue: https://github.com/sdkman/sdkman-db-migrations/issues/443
This PR adds all versions of Scala 2.10.x in the `ScalaMigrations` class.
=> Add support for older Scala versions

src/main/scala/io/sdkman/changelogs/package.scala
Add support for `LINUX_ARM32SF` and `LINUX_ARM32HF` platforms and retires `LINUX_ARM32`.
=> Support Linux ARM32 variants.

src/main/scala/io/sdkman/changelogs/MavenMigration.scala
These historical Maven 3.x versions are also available on https://archive.apache.org/dist/maven/maven-3, and I feel it would be useful to also have these available to pick from, alongside the prior versions that are already there.
=> Add Maven versions 3.3.3 to 3.0.4

src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
This is my first contribution to this repository, so please advise on any style or process mistakes.
An existing PR is open for 3.3.0 but is stalled: https://github.com/sdkman/sdkman-db-migrations/pull/605
The `./gradlew clean run` completes successfully on my machine with this PR's changes, but I had to use the command `docker run -d -p 27017:27017 --name=mongo arm64v8/mongo:4.0.28` to setup Mongo on my machine, which differs from the example on the README because I am on Apple silicon and Docker Hub doesn't have a mongo `3.2` for `arm64`.
I did _not_ test if the `sdk install spark 3.3.1` will succeed with this PR's changes, because I am not sure how to hook up my local SDKMAN with the mongoDB container...
So, tl;dr, I followed the patterns I see in Git closely. Happy to change, test, or …
=> Add Spark 3.2.2, 3.3.0, and 3.3.1

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
Updated the tomcat versions to the latest versions available and removed old, obsolete ones.
- Adding latest Versions of Tomcat 8 - 11
- Removed obsolete Tomcat 7 which is EOL since 2021
- Removed obsolete Tomcat 10.0 that is EOL since End of January 2023
- Removed 10.1.0-M8 milestone version that was superseded by final 10.1 version
=> Add current tomcat versions and remove EOL ones

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
This includes
- Tomcat 8.5.88 as latest from 8.5 line
- Tomcat 9.0.74 as latest from 9.0 line
- Tomcat 10.1.8 as latest from 10.1 line (will be new default version)
- Tomcat 11.0.0-M5 as latest from 11 line (this is the latest alpha release)
Tomcat 10.0.0-M3 dropped because it's only an alpha release and superseded by M5.
=> Upgraded to Tomcat April release versions

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
This includes
- Tomcat 8.5.89 as latest from 8.5 line
- Tomcat 9.0.75 as latest from 9.0 line
- Tomcat 10.1.9 as latest from 10.1 line (will be new default version)
- Tomcat 11.0.0-M6 as latest from 11 line (this is the latest alpha release)
Tomcat 10.0.0-M5 dropped because it's only an alpha release and superseded by M6.
=> Upgraded to Tomcat May release versions

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
This includes
- Tomcat 8.5.90 as latest from 8.5 line
- Tomcat 9.0.76 as latest from 9.0 line
- Tomcat 10.1.10 as latest from 10.1 line (will be new default version)
- Tomcat 11.0.0-M7 as latest from 11 line (this is the latest alpha release)
Tomcat 10.0.0-M6 dropped because it's only an alpha release and superseded by M7.
=> Upgraded to Tomcat June release versions

.github/workflows/pr.yml
> Avoid using this event if you need to build or run code from the pull request.
According to the `pull_request_target`
[docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target)
=> Use pull_request

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
This includes
- Tomcat 8.5.91 and 8.5.92 from 8.5 line
- Tomcat 9.0.78 and 9.0.79 from 9.0 line
- Tomcat 10.1.11 and 10.1.12 from 10.1 line (10.1.12 will be new default version)
- Tomcat 11.0.0-M10 as latest from 11 line (this is the latest alpha release)
Tomcat 11.0.0-M7 dropped because it's only an alpha release and superseded by M10.
=> Upgraded to Tomcat July & August release versions

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
Fixes several Tomcat CVE:
- Important: Request smuggling CVE-2023-45648
- Important: Denial of Service CVE-2023-44487
- Important: Information Disclosure CVE-2023-42795
- Low: Denial of Service CVE-2023-42794
- Tomcat 8.5.94 from 8.5 line
- Tomcat 9.0.81 from 9.0 line
- Tomcat 10.1.14 from 10.1 line (will be new default version)
- Tomcat 11.0.0-M12 as latest from 11 line (this is the latest alpha release)
Tomcat 11.0.0-M10 dropped because it's only an alpha release and superseded by M10.
=> Upgraded to Tomcat Oktober security release

src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
Hi! I contributed to these Spark migrations once before here (https://github.com/sdkman/sdkman-db-migrations/pull/614), so I followed the same pattern again in this PR.
Unfortunately, my local `./gradlew clean run` is failing with this:
```
Caused by: com.github.mongobee.exception.MongobeeChangeSetException: Invalid url: https://cdn.cuba-platform.com/cuba-cli/1.0.1/cuba-cli-1.0.1-linux.zip
```
but it appears unrelated to my changes, and the GitHub PR build succeeded, so hopefully that's not a blocker.
Thanks!
=> Add Spark 3.4.1 and 3.5.0

src/main/scala/io/sdkman/changelogs/FlinkMigrations.scala
Hello all,
This is my first attempt at contributing to SDKMAN. Thank you for this great tool.
I'm trying to add Flink versions 1.17.1 and 1.18.0 but couldn't run `./gradlew clean run` locally on my machine. It seems that no Docker container gets launched. Should that be the case?
I get the following:
```
[main] INFO org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
[cluster-ClusterId{value='6542d1704842cfe48ed1ea22', description='null'}-localhost:27017] INFO org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
at …
```
=> flink: add versions 1.17.1 and 1.18.0

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
- Tomcat 8.5.100 from 8.5 line
- Tomcat 9.0.88 from 9.0 line
- Tomcat 10.1.20 from 10.1 line (will be new default version)
- Tomcat 11.0.0-M19 as latest from 11 line (this is the latest alpha release)
Tomcat 11.0.0-M12 dropped because it's only an alpha release and superseded by M19.
=> Upgraded to Tomcat April '24 release

src/main/scala/io/sdkman/changelogs/JExtractMigrations.scala
@marc0der @aalmiray
The jextract guys finally moved the binary to bin and make use of an embedded JDK which resides in a different folder.
=> feat: Add jextract candidate

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
- Tomcat 9.0.95 from 9.0 line
- Tomcat 10.1.30 from 10.1 line (will be new default version)
- Tomcat 11.0.0-M26 as latest from 11 line (this is the latest beta release)
Tomcat 11.0.0-M19 dropped because it's only an alpha release and superseded by M26.
=> Upgraded to Tomcat September '24 release

src/main/scala/io/sdkman/changelogs/JExtractMigrations.scala
Adjusts the versioning to be similar to that of Oracle JDK EA versions.
=> chore: Improve jextract versioning

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
Tomcat 9.0.96 from 9.0 line
Tomcat 10.1.31 from 10.1 line (will be the new default version)
Tomcat 11.0.0 is the latest from 11 line (this is the latest beta release)
Tomcat 11.0.0-M26 dropped because it's only an alpha release and was superseded by GA.
=> Upgrade to Tomcat October '24 release

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
- Tomcat 9.0.100 from 9.0 line
- Tomcat 10.1.36 from 10.1 line
- Tomcat 11.0.4 from 11.0 line (will be new default version)
- Tomcat 7 is EOL 31 March 2021
- Tomcat 8 is EOL 31 March 2024
=> Tomcat February update

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
- Tomcat 9.0.102 from 9.0 line
- Tomcat 10.1.39 from 10.1 line
- Tomcat 11.0.5 from 11.0 line (will be new default version)
The Tomcat releases 9.0.101, 10.1.37 and 10.1.38 have been skipped by Tomcat team.
=> Upgraded to Tomcat March '25 release

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
This release fixes CVE-2025-31650 and CVE-2025-31651.
- Tomcat 9.0.104 from 9.0 line
- Tomcat 10.1.40 from 10.1 line
- Tomcat 11.0.6 from 11.0 line (will be the new default version)
Tomcat team has skipped the Tomcat release 9.0.103.
=> Upgraded to Tomcat April '25 release

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
- Tomcat 9.0.105 from 9.0 line
- Tomcat 10.1.41 from 10.1 line
- Tomcat 11.0.7 from 11.0 line (will be the new default version)
=> Upgraded to Tomcat May '25 release

src/main/scala/io/sdkman/changelogs/TomcatMigration.scala
- Tomcat 9.0.108 from 9.0 line
- Tomcat 10.1.44 from 10.1 line
- Tomcat 11.0.10 from 11.0 line (will be the new default version)
=> Upgraded to Tomcat August '25 release
